# Generated by Django 5.0.2 on 2024-02-12 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='mailing_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='mailing_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
